name: 📽️Youtube Videos
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCLJY3Fa0xheb_SNSuPkbdZw
          comment_tag_name: YOUTUBE-CARDS
          youtube_api_key: ${{ secrets.YT_API }}
          show_duration: true
